arch:
  - amd64
  - arm64

language: go

go:
  - 1.13.x
  - 1.12.x

dist: xenial

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $GOPATH/pkg/mod

matrix:
  fast_finish: true

env:
  global:
    - GO111MODULE=on

go_import_path: github.com/containous/yaegi

before_install:
  # Install linters and misspell
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin ${GOLANGCI_LINT_VERSION}
  - golangci-lint --version

install:
  - echo "TRAVIS_GO_VERSION=$TRAVIS_GO_VERSION"
  - go mod download

before_script:
  - rm -f interp/op.go interp/interp_test.go
  - make generate
  - git update-index -q --refresh
  - CHANGED=$(git diff-index --name-only HEAD --)
  - test -z "$CHANGED" || echo $CHANGED
  - test -z "$CHANGED"

script:
  - make check
  - go build -v ./...
  - make tests

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $STABLE = true
