// Code generated by 'goexports net/http/cookiejar'. DO NOT EDIT.

// +build go1.14,!go1.15

package stdlib

import (
	"net/http/cookiejar"
	"reflect"

	"github.com/containous/yaegi/interp"
)

func init() {
	Symbols["net/http/cookiejar"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New": reflect.ValueOf(cookiejar.New),

		// type definitions
		"Jar":              reflect.ValueOf((*cookiejar.Jar)(nil)),
		"Options":          reflect.ValueOf((*cookiejar.Options)(nil)),
		"PublicSuffixList": reflect.ValueOf((*cookiejar.PublicSuffixList)(nil)),
	}
}
func (_w Wrapper) PublicSuffix(domain string) string {
	_f := interp.Method("PublicSuffix", _w.Wrap).(func(domain string) string)
	return _f(domain)
}
